apiVersion: apps/v1
kind: Deployment
metadata:
  name: wazuh-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wazuh-webhook
  template:
    metadata:
      labels:
        app: wazuh-webhook
    spec:
      containers:
      - name: webhook
        image: allenku0/wazuh-webhook:v1.2
        imagePullPolicy: Always
        ports:
        - containerPort: 8443
        volumeMounts:
        - name: tls
          mountPath: /tls
          readOnly: true
      volumes:
      - name: tls
        secret:
          secretName: wazuh-webhook-tls
